export const dummyData = [
  {
    id: "1",
    firstName: "Bob",
    lastName: "Johnson",
    email: "bjohnson@gmail.com",
    phone: "773-123-4567",
    address: "123 Main St",
    postalCode: "60614",
    city: "Chicago",
    state: "IL",
    label: "Friends",
    new: false
  },
  {
    id: "2",
    firstName: "Susan",
    lastName: "Smith",
    email: "ssmith@gmail.com",
    phone: "773-144-3563",
    address: "1456 N. Ashland",
    postalCode: "60647",
    city: "Chicago",
    state: "IL",
    label: "Family",
    new: false
  },
  {
    id: "3",
    firstName: "Sam",
    lastName: "Evans",
    email: "samevans@yahoo.com",
    phone: "312-256-9365",
    address: "1456 Western",
    postalCode: "60601",
    city: "Chicago",
    state: "IL",
    label: "Other",
    new: false
  },
  {
    id: "4",
    firstName: "Anne",
    lastName: "Withers",
    email: "awithers@gmail.com",
    phone: "312-544-9384",
    address: "1456 N. Broadway",
    postalCode: "60606",
    city: "Chicago",
    state: "IL",
    label: "Work",
    new: false
  },
  {
    id: "5",
    firstName: "Tony",
    lastName: "Robertson",
    email: "trobertson@gmail.com",
    phone: "773-982-2398",
    address: "1456 N. Milwaukee",
    postalCode: "60647",
    city: "Chicago",
    state: "IL",
    label: "Family",
    new: false
  },
  {
    id: "6",
    firstName: "Eric",
    lastName: "Ericson",
    email: "eericson@gmail.com",
    phone: "773-923-3333",
    address: "1342 N. Sawyer",
    postalCode: "60647",
    city: "Chicago",
    state: "IL",
    label: "Friends",
    new: false
  },
  {
    id: "7",
    firstName: "Jessica",
    lastName: "Samson",
    email: "jsamson@gmail.com",
    phone: "773-345-8985",
    address: "1232 N. Clark",
    postalCode: "60614",
    city: "Chicago",
    state: "IL",
    label: "Other",
    new: false
  },
  {
    id: "8",
    firstName: "Betty",
    lastName: "Fredrickson",
    email: "bfredrickson@gmail.com",
    phone: "312-123-0039",
    address: "1232 N. Clark",
    postalCode: "60614",
    city: "Chicago",
    state: "IL",
    label: "Work",
    new: false
  },
  {
    id: "9",
    firstName: "Tom",
    lastName: "Gregory",
    email: "tgregory@gmail.com",
    phone: "312-546-8475",
    address: "2435 N. Barry",
    postalCode: "60614",
    city: "Chicago",
    state: "IL",
    label: "Family",
    new: false
  },
  {
    id: "10",
    firstName: "Sandra",
    lastName: "Tomlin",
    email: "stomlin@gmail.com",
    phone: "773-545-1122",
    address: "1324 N. Clark",
    postalCode: "60614",
    city: "Chicago",
    state: "IL",
    label: "Friends",
    new: false
  },
];